spring:
  redis:
    host: 192.168.0.85
    port: 6379
    password: deviskaifa
    database: 7

server:
  port: 7788

#resilience4j.bulkhead:
#  instances:
#    backend-pushToAll:
#      maxConcurrentCalls: 10

resilience4j.ratelimiter:
  instances:
    backend-pushToAll:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100